# Generated by Django 2.0.1 on 2020-02-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PestCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uploaded_image', models.ImageField(upload_to='Leaves')),
                ('crop_name', models.CharField(max_length=254)),
            ],
        ),
    ]
