# Generated by Django 2.0.1 on 2020-02-02 17:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_auto_20200131_2153'),
        ('admin', '0004_auto_20200131_2153'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userdetail',
        ),
    ]
